creation_rules:
  - path_regex: '^secrets/kubernetes/.*\.sops\.yaml$'
    encrypted_regex: '^(data|stringData)$'
    age: age1e0seaf79awzr4980vr6w3w3z3urvn6sp5m4l58fn3829jzsxrg2q4up9vz
  - path_regex: '^secrets/.*\.sops\.yaml$'
    age: age1e0seaf79awzr4980vr6w3w3z3urvn6sp5m4l58fn3829jzsxrg2q4up9vz
