---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/extndr/proxmox-k8s.git
    targetRevision: main
    path: gitops/platform/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/warn: restricted
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - FailOnSharedResource=true
    retry:
      limit: 10
      refresh: true
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
