---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: ghcr.io/rancher/local-path-provisioner/charts
    chart: local-path-provisioner
    targetRevision: "0.0.36"
    helm:
      releaseName: local-path-provisioner
      valuesObject:
        storageClass:
          defaultClass: false
          name: local-path
          reclaimPolicy: Delete
          volumeBindingMode: WaitForFirstConsumer
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - FailOnSharedResource=true
    retry:
      limit: 5
      refresh: true
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
