---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pve-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    token-value: AgCpMp+7zQKnfF3ot4n5bZnPu1UYNpJzDgIgnmmSM8m4oVNVZ7in9ntY+72FcHGjlY5nPQgYBMql4r8Iil4DVrY7xelrHGYR+LMVPqRtiYf6yDVNQLRrbmUncvK9uNZxttP/3QCytc/GS7GgJKcgP5iPBKIj5+RAuItNgy0EaL0M6Ayl3Z6UuJYEC9t/TX2qizaWZyXFIS3q9ICjmqsl/WfSSVuliehKumrENJyq+c3beyw5/z8eW3FUB73WlghcCFm6j2PXbuKBOyUClJYRXZ/PveAnzfRB1OilwFzsQNdDPUB6hsHAkAqReOmeceTqhWS5j7m3lXMTBm6KdEGKhD3taY5t4UFx/8DbdvArfm+3+/jR+ZFeT1UEdHf0IIEh8efwovITfk5CKhkmRdN9rI1gYlgwKudr85E29m47UnW3bjCYKbcv4Pk/AR6MANlCj+L28uWBFiHtG8ymGl26AT5PoPZT66ZYTznHHKekI0kT3Zt/LD6FnnQ4jc+OygoMkLc9IOwX8Dw2rwRj8nQ98FOBE0Ncjt5iAbwdjCls+xtBUFmsKUihXvjgt/6YOchCfhMCrD67cYU4gl6jbuIZpRmCYfF+ZR58wzSKp0ZCHjVV8DrxVfW+9RHqzYSJJoqBFl9mK+5zPc5hk2uWjalwF8hKCreFBPL5lFS7fJ+McFqfuigIzEs2SwW7Q7xMb47WSB4fxAm0It2m04OAKxsjjOXkidYIb7na9nqdzfrtJJBeB07BZuw=
  template:
    metadata:
      name: pve-exporter-credentials
      namespace: monitoring
