---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: demo
spec:
  encryptedData:
    password: AgA4yPIomGzgoRuulzM371DXfvlO7RzC6kqvDt0KEYF+YHYTxEyj8wwCrtnJZiv5d6SycGK6VriLWcxYgeRlGmRA3J/z0CuzT+rpZRprTT8SKjk2eg4OS/K962cdYCGOHrMVMZpreuzkSw39pBZQyW7IhLjp6eBlFgz0Lry646QCfq2fXkcroQISNb5NTWWNI8kH6LRjL61MDv/GJ9y8JmXINuKuofKoob49wWI+Pi3iNtpwi+IH28Yww/7RDGvxSZtCDiOe+rGUOIw1MHPcnQ328d7aQR6l1KiVv6OlP1C5dfrS6GwfUz7kBsCRsvBlvDpeTAAGFkk6VfVMx9DiGygA7h7ONmNgvt87YxhIqtQ0tXs/i7HXBI40SpWjPCYjoyX9kUEAvp/PQutt3XEmvZ8x+tNVkCsgHZYNE4FyjAYgJ4bzJQNGLc8SYHPjpIAYvUJnAtcdYQtFeGaFqRQyHkjJ8yPqg3xguPGLG7s8Pkw98PpfxvMp7MjPsPyaST5uVRBTD/5yk8DDVgX8s9HDJDxjoXdzlvlu47xGY4CI9KZnO43J5Nms951bJtCxbyG8m0p12LtBz+B3vRqYCfwiyrrz3mqsZe9hcLH3nzEMDzmL8klXOLNkXopz2yB/oPgLaXhOoc+VhjkBdxWV99fKmsua29XwRad+yM5xLKymaAh900jXKNrySeC709OS/3zSMJRZCdqa552KgR6+x72Xhivq1us0Yxex+sUwgcczyxOCcsGXzwGFlUb5FvLLozXXIsY=
  template:
    metadata:
      name: postgres-credentials
      namespace: demo
