apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- deployment.yml
- service.yml
- httproute.yml
- pdb.yml
images:
- digest: sha256:dfa6b71ca28f242de2d2ce13761b951309253ee54480eb182b86ce3187e4381f
  name: demo-app
  newName: ghcr.io/extndr/proxmox-k8s-demo-app
