---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - deployment.yml
  - service.yml
  - httproute.yml
  - pdb.yml
images:
  - name: demo-app
    newName: ghcr.io/extndr/proxmox-k8s-demo-app
    newTag: main
