apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- deployment.yml
- service.yml
- httproute.yml
- pdb.yml
- servicemonitor.yml
images:
- digest: sha256:2079ca1cedc8f055e734f1f0495a6a384b87cab6a893cac6fa4ebf8011ee10cd
  name: demo-app
  newName: ghcr.io/extndr/proxmox-k8s-demo-app
