---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
  labels:
    monitoring: platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
